version: "2"

services:
  php56_standard:
    build:
      context: .
      dockerfile: Dockerfile.php56
    ports:
      - "5601:80"
    volumes:
      - ./main:/var/www
    environment:
      - APP_ENV=development
      - APP_VHOST=standard

  php56_symfony:
    build:
      context: .
      dockerfile: Dockerfile.php56
    ports:
      - "5602:80"
    volumes:
      - ./main:/var/www
    environment:
      - APP_ENV=development
      - APP_VHOST=symfony

  php70_standard:
    build:
      context: .
      dockerfile: Dockerfile.php70
    ports:
      - "7001:80"
    volumes:
      - ./main:/var/www
    environment:
      - APP_ENV=development
      - APP_VHOST=standard

  php70_symfony:
    build:
      context: .
      dockerfile: Dockerfile.php70
    ports:
      - "7002:80"
    volumes:
      - ./main:/var/www
    environment:
      - APP_ENV=development
      - APP_VHOST=symfony

  php71_standard:
    build:
      context: .
      dockerfile: Dockerfile.php71
    ports:
      - "7101:80"
    volumes:
      - ./main:/var/www
    environment:
      - APP_ENV=development
      - APP_VHOST=standard

  php71_symfony:
    build:
      context: .
      dockerfile: Dockerfile.php71
    ports:
      - "7102:80"
    volumes:
      - ./main:/var/www
    environment:
      - APP_ENV=development
      - APP_VHOST=symfony