version: "2"

services:
  php56_standard:
    build:
      context: .
      dockerfile: Dockerfile.php56
    ports:
      - "50561:80"
    volumes:
      - ./main:/var/www
    environment:
      - APP_ENV=development
      - APP_VHOST=standard

  php56_symfony:
    build:
      context: .
      dockerfile: Dockerfile.php56
    ports:
      - "50562:80"
    volumes:
      - ./main:/var/www
    environment:
      - APP_ENV=development
      - APP_VHOST=symfony

  php70_standard:
    build:
      context: .
      dockerfile: Dockerfile.php70
    ports:
      - "50701:80"
    volumes:
      - ./main:/var/www
    environment:
      - APP_ENV=development
      - APP_VHOST=standard

  php70_symfony:
    build:
      context: .
      dockerfile: Dockerfile.php70
    ports:
      - "50702:80"
    volumes:
      - ./main:/var/www
    environment:
      - APP_ENV=development
      - APP_VHOST=symfony

  php71_standard:
    build:
      context: .
      dockerfile: Dockerfile.php71
    ports:
      - "50711:80"
    volumes:
      - ./main:/var/www
    environment:
      - APP_ENV=development
      - APP_VHOST=standard

  php71_symfony:
    build:
      context: .
      dockerfile: Dockerfile.php71
    ports:
      - "50712:80"
    volumes:
      - ./main:/var/www
    environment:
      - APP_ENV=development
      - APP_VHOST=symfony