#!/bin/sh

docker pull elnebuloso/php-apache:php56-latest \
&& docker run --name php-apache56 -p=8056:80 -e APP_VHOST=standard -e APP_ENV=development -d elnebuloso/php-apache:php56-latest

docker pull elnebuloso/php-apache:php70-latest \
&& docker run --name php-apache70 -p=8070:80 -e APP_VHOST=standard -e APP_ENV=development -d elnebuloso/php-apache:php70-latest

docker pull elnebuloso/php-apache:php71-latest \
&& docker run --name php-apache71 -p=8071:80 -e APP_VHOST=standard -e APP_ENV=development -d elnebuloso/php-apache:php71-latest