#!/bin/bash

################################################################################################

set -e
rm -f "$APACHE_PID_FILE"

################################################################################################

# user defined apache vhost
FILE=/var/www/.docker/apache2/vhost.$APP_VHOST.$APP_ENV.conf

if [ -f $FILE ]; then
    cp $FILE /etc/apache2/sites-available/vhost.$APP_VHOST.$APP_ENV.conf
fi

################################################################################################

ln -nsf /etc/apache2/sites-available/vhost.$APP_VHOST.$APP_ENV.conf /etc/apache2/sites-enabled/000-default.conf
exec /usr/sbin/apache2ctl -D FOREGROUND

################################################################################################